### ISSUE TITLE
请问可以使用代理么？

### ISSUE THREAD

**Issue by zaang** [HeddaZ/Shadowin#1]
办公室会屏蔽一些网址，我想可能是因为这样，我这里看不到数据，有没有能配置代理的途径？

**Comment by HeddaZ** [comment]
我们也是公司网络。这个窗体其实就是 IE 浏览器包装的，所以你只要配好 IE 的代理即可。
----------------------------------------------------------------------------------------------------------------------
* 还有另一个方案就是，将源码 ShadowStock 目录下载下来，随便放到一个路径上（或配置为一个 IIS 本地 URL，纯静态的即可），然后修改 Shadowin.exe.config 中  <add key="Url" value="{你的本地URL}"/> 。这样的数据源刷新是使用 iframe 包含新浪 http://hq.sinajs.cn/rn={0}&list={1} 实现的，也只需要你的浏览器设定好代理即可。
