### ISSUE TITLE
不支持xp系统？

### ISSUE THREAD

**Issue by laolangcool** [HeddaZ/Shadowin#10]
在xp上运行，提示 The application failed to initialize properly (0xc0000135). Click on OK to terminate the application.

**Comment by laolangcool** [comment]
看了软件介绍，猜测是没装netframework的原因。因为有一台电脑较老，也不方便装，如果能去掉这个依赖就好了 :)
发现另一款股票悄悄看就没有这个依赖…

**Comment by HeddaZ** [comment]
抱歉哦，虽然目前已经有 framework 的提取方案，但是本人还是倾向于使用微软官方的运行时； 2.0 框架也是默认配置了，所以暂不会考虑此方案
