### ISSUE TITLE
希望能修改窗口默认坐标位置

### ISSUE THREAD

**Issue by cppapp** [HeddaZ/Shadowin#12]
现在打开后始终都是处于桌面右下角。希望能给出设置默认初始坐标的配置方式。或者允许窗口拖动也行。

**Comment by HeddaZ** [comment]
本软件最初的想法是【简单粗暴的隐蔽】，右下角其实是一个视角比较自然且容易隐藏的位置。
-- 所以，你是否可以简单说一下这个想法的理由和应用场景呢？

**Comment by babysource** [comment]
比如两个显示器，我希望能移动到副显示器的右下角并锁定位置

**Comment by jjj346** [comment]
关于窗口位置的，也是有同样的需求，希望能移到副显示器的窗口下

**Comment by HeddaZ** [comment]
To support multiple screens in R2.2.
By adjust ScreenId in config file.

52cdf1bf6eefe4a70b0a81295b91e8e735bc0eca
