### ISSUE TITLE
建议增加鼠标点击穿透功能.

### ISSUE THREAD

**Issue by clownsean** [HeddaZ/Shadowin#14]
感谢作者,非常好用的小工具.
半透明 只看就够了,鼠标能穿透点击到背后的窗口才好
感谢了.

**Comment by HeddaZ** [comment]
Hi, 非常时髦的点子。
目前显示区域其实也是一个 windows 窗体配合了一个浏览器外壳，所以此想法在当前架构下有些难以实现。
我暂时记录下来，看未来是否有必要开发一个直接基于 绘制API 的【只读】版本分支。

**Comment by HeddaZ** [comment]
目前架构下应无法实现。
