### ISSUE TITLE
快捷键自定义

### ISSUE THREAD

**Issue by 7Eric9** [HeddaZ/Shadowin#17]
如果想把ctrl+-改为ctrl+shift+-，配置文件里应该如何设置呢？
`    <add key="DecreaseOpacityHotKeyModifierKey" value="Control"/>
    <add key="DecreaseOpacityHotKeyKey" value="OemMinus"/>`

**Comment by HeddaZ** [comment]
减号的代码是  OemMinus，
参考：
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?redirectedfrom=MSDN&view=netframework-4.8
