### ISSUE TITLE
能否增加一个自选基金功能？

### ISSUE THREAD

**Issue by sunhiro** [HeddaZ/Shadowin#19]
如果再有基金功能，就完美了。一次性付费的话可以考虑购买。

**Comment by HeddaZ** [comment]
新浪基金的数据源格式和股票有些差异，可能考虑在后续版本中加入。

**Comment by HeddaZ** [comment]
#27 类似问题

**Comment by HeddaZ** [comment]
近期已升级如下支持：沪深、基金、新三板、债券、港股、美股。
无须手工升级，自动生效！
----------------
若有心支持本项目，扫码捐献即可。暂时没有精力操作付费运营 :)
