### ISSUE TITLE
希望股票代码能写到配置文件里

### ISSUE THREAD

**Issue by laolangcool** [HeddaZ/Shadowin#2]
希望能支持把关注的股票代码写到单独的配置文件里，这样备份和导入就很方便了。并且配置文件里还可以为代码进行注释。

**Comment by HeddaZ** [comment]
您的反馈已收到，我会尽快考虑此功能的实现方式；
--------------------------------------
因为目前的 shadowstock 通过 HTML / Cookie 来提供数据记录，它在远程 http 服务器上（因此才如此轻量），所以唯一能有权限往本地写的就是 cookie。

** 我会考虑更实际有效的方案来实现【股票代码的迁移问题】，也许加一个账号关联是个可行的方案。**

**Comment by laolangcool** [comment]
账号感觉必要性不强，就是看股市行情，不用太复杂，现在这样简单小巧的好。能读取本地的关注代码文件就可以了，类似配置文件那样。

**Comment by HeddaZ** [comment]
谢谢你的建议，因为 Shadowin 透明外框和内层的 ShadowStock 页面原本是分开的2个项目；只是结合起来用会比较方便，所以才一起翻出来开源。
目前外框还不会向内部页面注入任何的信息，我也尽量不去产生这样的耦合。因此具体的方案还需要斟酌一下。

**Comment by laolangcool** [comment]
理解。那能否这样：让目前的输入框支持从外部拷贝带回车和注释的内容进来，ss把内容解析出来？

**Comment by HeddaZ** [comment]
问题已在 V2.0 中解决，请重新下载安装：https://github.com/HeddaZ/Shadowin/releases  （推荐升级方式）
抑或直接修改本地文件 `Shadowin.exe.config`：
&lt;add key=&quot;Url&quot; value=&quot;http://shadowstock.iihtml.com/&quot;/&gt;
