### ISSUE TITLE
脚本错误弹窗

### ISSUE THREAD

**Issue by TANSHUAI1001** [HeddaZ/Shadowin#20]
每次打开都弹出“当前页面的脚本发生错误。”
https://tpc.googlesyndication.com/pagead/js/r20180228/r20110914/abg.js
隐藏和显示切换的时候也会弹出。
这个能不能优化下？

**Comment by HeddaZ** [comment]
一般类似情况都是因为 IE 的核心版本太低；
可以考虑升级一下系统或者 IE。
实在不想升级，可以使用 v1 版本；此版本近期我已不再 host；您可以下载源码自行建一个 WEB 站点即可。
