### ISSUE TITLE
内存管理建议加强

### ISSUE THREAD

**Issue by CACppuccino** [HeddaZ/Shadowin#23]
![image](https://user-images.githubusercontent.com/25502039/43627320-31fd3c34-9739-11e8-8032-cd888c26e10c.png)
如图所示，跟其它几个软件对比，这个软件的内存管理上似乎有一些问题，期待加强

**Comment by HeddaZ** [comment]
您好，目前我这里使用，还有朋友圈使用没有遇到类似情况。我本机上的程序也是常年不关闭的。
可能要麻烦您检查一下是否本地存在一些杀毒软件、或者浏览器插件产生交互影响。
Shadowin使用的是 windows internet explorer 核心呈现网页，因此任何基于 IE 的额外设置都会导致内存管理失控。

**Comment by HeddaZ** [comment]
No response.
