### ISSUE TITLE
怎么看黄金呢

### ISSUE THREAD

**Issue by Brunofan** [HeddaZ/Shadowin#26]
我试了代码 AUTO，AU0，都不行啊

**Comment by HeddaZ** [comment]
您好，由于目前新浪数据源格式的兼容问题，暂时还不能提供黄金关注功能。

**Comment by HeddaZ** [comment]
近期已升级如下支持：沪深、基金、新三板、债券、港股、美股。
已经确认对于黄金，新浪的suggestion数据源无法取到，因此无法实现。
