### ISSUE TITLE
Win7 64系统下(虚拟机),设置菜单不显示

### ISSUE THREAD

**Issue by lubocheng** [HeddaZ/Shadowin#28]
如下图:
![image](https://user-images.githubusercontent.com/3746672/69407315-34504d00-0d3f-11ea-9830-3becbe407e56.png)

**Comment by HeddaZ** [comment]
您好，这个问题是个已知bug，并非只有虚拟机中重现。
原因是因为选中的显示栏位数量超过了URL参数可以支持的最大长度，v2.2 中采用修改 IIS 配置的 workaround 临时解决；
此问题在 v2.3 中正式通过 cookie 传参解决。
