### ISSUE TITLE
windows版本中,我能否定义默认窗体位置?

### ISSUE THREAD

**Issue by MrLiuRen** [HeddaZ/Shadowin#29]
您好,默认打开即位于屏幕右下角, 我想调整到左下角, 这个能通过参数修改吗?谢谢!

**Comment by HeddaZ** [comment]
不好意思，这个功能目前不支持，逻辑仅按照右下角的方式计算位置。
但是程序可以支持多屏显示，只要修改 <add key="ScreenId" value="0"/> 即可。
