### ISSUE TITLE
Cloudfare拦截

### ISSUE THREAD

**Issue by bravotok** [HeddaZ/Shadowin#30]

**Comment by HeddaZ** [comment]
能明确一些问题吗？

**Comment by bravotok** [comment]
公司会屏蔽当前域名（可能是因为域名里带了stock）

所以不得已要用astrill挂代理使用

使用astrill时无论用哪个节点（包括香港、USA、台湾、韩国）都会导致cloudfare提示拦截

 

而且只有在shadowstock上会出现这个问题，浏览其他使用cloudfare的网站均不会出现此错误

 

发件人: 大飞飞 <notifications@github.com> 
发送时间: 2020年2月27日 14:31
收件人: HeddaZ/Shadowin <Shadowin@noreply.github.com>
抄送: bravotok <bravotok@icloud.com>; Author <author@noreply.github.com>
主题: Re: [HeddaZ/Shadowin] Cloudfare拦截 (#30)

 

能明确一些问题吗？

**Comment by HeddaZ** [comment]
您好，
这个情况可能是由于您使用的代理软件误判，目前 stock.plusii.com 已经彻底迁回国内腾讯云服务器，域名也使用 DNSPOD 方案；完全没有使用 cloudfare 一类加速方案。

针对此情况，我临时开通了另一个二级域名协助您验证问题所在，绕过公司限制，请将 Shadowin.exe.config 中的这一行修改为：
<add key="Url" value="http://ss.plusii.com/"/>

--- 修改之前请先【导出】选股列表的设置。

**Comment by HeddaZ** [comment]
之前有其它用户提到空白列表和无法进行关键字选股等现象；后来发现是某些新浪的域名被公司防火墙屏蔽造成的；
因此我前段时间用反向代理托管了新浪的2个数据源，您可以看一下这个问题是否已经同时被解决。
