### ISSUE TITLE
本来想添加道琼斯指数的，但是显示添加成功后，页面上的所有信息都没有了，而且显示当前及页面脚本发生错误

### ISSUE THREAD

**Issue by abc072** [HeddaZ/Shadowin#31]
http://hq.sinajs.cn/?rn=1585203929137&list=sh000001,sz399006,rt_hk00700,gb_.dji,sz300495,
请问该如何解决？
重新下载软件使用无效，一直报错。

**Comment by HeddaZ** [comment]
,gb_.dji 这个程序没考虑到，道琼斯指数标记里含有一个 点，导致链接失效。

**Comment by HeddaZ** [comment]
可以通过清楚本地 IE 浏览器的 缓存来解决。
针对道琼斯指数的问题，我会尽量修复。

**Comment by HeddaZ** [comment]
此问题已升级网页端修复，所有用户自动生效；客户端无需升级。
