### ISSUE TITLE
场内基金没办法获取

### ISSUE THREAD

**Issue by MayApril** [HeddaZ/Shadowin#34]
感谢作者，很喜欢这个作品。
但是目前发现一个变动：之前可以搜到场内基金的，目前2.4-2.5版本没办法搜索了，请教一下是怎么回事？

**Comment by HeddaZ** [comment]
自 2.4 左右，新浪suggest的数据源有些调整，他们废弃了之前一直都很好用的 suggest2。
所以我也对应的过滤了一些支持不好的代码类型，关于您提到的场内基金，是否可以给我几个基金代码，最好也给一下对应新浪页面的 URL，这样我可以针对性的改善。

**Comment by 15003900500** [comment]
我也有这个情况，7月31日开始软件突然自动重置所有设置和添加的股票信息，之后就无法搜索到场内基金了，比如512480.SH，515750，501057等这些。

**Comment by idacd** [comment]
自7月31日开始我也出现了这个问题，当时软件自动重置了所有设置，然后我重新调整的时候发现场内基金没办法加入进去了，比如512480，515750，501057这些，都无法搜索添加

**Comment by idacd** [comment]
> 自 2.4 左右，新浪suggest的数据源有些调整，他们废弃了之前一直都很好用的 suggest2。  所以我也对应的过滤了一些支持不好的代码类型，关于您提到的场内基金，是否可以给我几个基金代码，最好也给一下对应新浪页面的 URL，这样我可以针对性的改善。

自7月31日开始我也出现了这个问题，当时软件自动重置了所有设置，然后我重新调整的时候发现场内基金没办法加入进去了，比如512480，515750，501057这些，都无法搜索添加

**Comment by HeddaZ** [comment]
切换到新数据源已做完适配，测试515750可以正常添加，请再验证一下效果。
