### ISSUE TITLE
win10  电脑无法显示

### ISSUE THREAD

**Issue by xiaofengtongxue** [HeddaZ/Shadowin#35]
![image](https://user-images.githubusercontent.com/17273994/89143703-113c9500-d57e-11ea-8582-12a7fce2116f.png)
![image](https://user-images.githubusercontent.com/17273994/89143712-1863a300-d57e-11ea-84e2-e9c6edf4e01f.png)
![image](https://user-images.githubusercontent.com/17273994/89143735-26b1bf00-d57e-11ea-8592-7258f95378e1.png)
配置host了，还是无法显示，win版本
![image](https://user-images.githubusercontent.com/17273994/89143775-434df700-d57e-11ea-9e4b-5f87b1714d12.png)

**Comment by HeddaZ** [comment]
请取消 hosts，目前我已经将外部数据源都转向了自己的反向代理，您只要确保能够打开首页，就可以正常使用所有功能了。
如果仍有问题，请用浏览器打开 stock.plusii.com 页面。 之后点 F12 看一下是否有错误。
