### ISSUE TITLE
常见问题参考

### ISSUE THREAD

**Issue by HeddaZ** [HeddaZ/Shadowin#43]
做了一次升级调查，结果炸出了好多用户问题，有时候并非软件未实现，而是大家都不知道 😅
为了大家能够更好的使用此工作，针对高频问题做个答复。持续更新中 ...
  
  
- 最近数据刷新有些不稳定？
> 确实是的，用了10年的新浪财经突然堵了我们的接口请求，不让用就不用吧，一不做二不休，花了1天时间全盘更换了腾讯财经数据源，反而发现腾讯的数据更规范，于是乘机也对代码做了一点优化。
> 由此事件也触发了我改进数据源性能的冲动，目前已经开坑了新的分支，并引入各种乱七八糟的牛逼技术来实现数据源中间件。

- 最多支持盯盘的股票数量？
> 目前已调整为25，考虑到性能体验，抱歉暂无法支持更大扩容；请等待后续的数据源中间件发布，可以带来比较明细的容量提示。

- 是否支持查看分时图、K线、MDAC等工具？
> 工具本身不支持，也不想把功能做得太张扬牺牲隐蔽性。但提供了网上的实时图形工具的链接，请在“设置”中显示“工具”栏位，点击“线”这个链接即可快速查看图形。

- 表格布局是否可以自行调整？
> 目前布局是根据界面宽度自适应的，不支持自定义表格布局。最大、最小界面宽度可以通过调整配置文件 Shadowin.exe.config / FormXXXSize 数值来自定义。

- 广告干扰很大？
> 初期投放广告的目的是借助流量补贴一些运营成本。既然好多用户都反映广告碍事，索性就删除广告了！如果您正好哪天抓了个涨停，希望爱心捐助支持一下项目，谢谢！关于菜单、退出窗口中都能看到捐赠二维码，金额随意。

- 支持更多的数据栏位？
> 切换腾讯数据源后，现在已经可以关注市盈率、换手率、成交量了，请自行在“设置”中定义。

- 如何长期保留影窗浏览器的设置？比如，窗体尺寸、透明度、缩放比例、多显示器 ...
> 请使用记事本打开配置文件 Shadowin.exe.config，搜索并调整其中的如下参数保存即可永远生效：
> |Opacity|窗体初始透明度|
> |FormMinimumSize|窗体最小尺寸|
> |FormMaximumSize|窗体最大尺寸|
> |FormSize|窗体初始尺寸(必须介于最大/最小值之间)|
> |ScreenId|多显示器时，在哪个显示器上显示窗体|
> |PageZoom|内容的初始缩放比例|

- 如何长期保留影子证券的设置？比如，股票列表、刷新率、自定栏位、模式 ...
> 不要怀疑，本工具设计初就智能支持长期保存影子证券的自定义设置。如果您的股票列表、自定义设置经常丢失，一定是因为有不正确的设置导致的。
> 1. 请确保 IE 浏览器打开了 Cookie 支持（检查点很多，请自行百度）；
> 2. 请确保 IE 浏览器没有设置为退出、重启时自动清除数据；也请确保各家杀毒、管家没有做这种傻不啦叽的事；
> 3. 再不济，请打开 Internet 选项，切换到“高级”选项卡，重置 Internet Explorer 设置；
> 4. 保险起见，请点击“设置”旁边的小箭头，导出自定义配置脚本另存；未来丢失亦可在此随时恢复。

- 本项目是否有付费计划？
> 统一回复一下：本项目完全靠爱发电，已持续为网友提供服务15年，流量不一定要转为效益，我仍希望保持工作之余的那一点热爱。本工具不做商业化计划，也是不希望被责任限制了空间。我只管分享、大家只管享用，简单就好。
> 顺便说一下，如果有程序员小伙伴对此项目感兴趣；请在 github 上联系我，非常期待能够一起开发 mac 版本和更多牛逼功能。

- 为什么会开发一些整活的功能？
> 例如，可以将”中国联通“的显示名自定义为”联不通“、”涨不动"。一方面，在单色模式下可以让股票列表更具迷惑性；另一方面，也证明程序员偶尔也会浪一下。
  
  
最后，QQ9812152 欢迎有问题沟通。

**Comment by pofycn7639** [comment]
快捷键是否可以自定义调整？有时候跟其他应用有冲突

**Comment by HeddaZ** [comment]
> 快捷键是否可以自定义调整？有时候跟其他应用有冲突

可以自定义的，请查看项目文档，修改 Shadowin.exe.config 配置即可。

**Comment by alienspy** [comment]
513520 查不到

**Comment by heddaz** [comment]
> 513520 查不到

这是 ETF，目前腾讯财经的建议源不支持，所以工具暂时也不支持。
