### ISSUE TITLE
建议使用配置文件方式保存数据

### ISSUE THREAD

**Issue by 273511049** [HeddaZ/shadowin#46]
建议使用配置文件方式保存数据

**Comment by HeddaZ** [comment]
感谢建议，这个要点曾经斟酌了好多次。但最终还是定为 cookie，主要还是考虑到 http://stock.plusii.com/ 站点可以脱离软件外壳被直接使用。
所以暂时不会实现选股列表的配置文件；仅仅是软件外观和行为使用了本地配置文件。
