### ISSUE TITLE
运行多个实例导致快捷键失效，无法退出

### ISSUE THREAD

**Issue by laolangcool** [HeddaZ/Shadowin#5]
因为sw不支持只运行一个实例，若打开了两个实例，新开的实例就不识别快捷键了。希望能修复，可能的办法：
1、在窗口上增设关闭按钮。
2、只允许运行一个实例。
因为不会有运行多个实例的场景吧，所以感觉第2个方法更好一些。

**Comment by HeddaZ** [comment]
感谢反馈，刚刚也有口头收到此问题；此问题会优先解决。
