### ISSUE TITLE
关于快捷键的全局应用

### ISSUE THREAD

**Issue by laolangcool** [HeddaZ/Shadowin#6]
sw能否支持定义快捷键是否全局或只在程序范围内，因为我喜欢只有显示/隐藏是全局的，而退出是sw窗口内的。像调整窗口大小和透明的，在程序内才有作用的才更加全理。

**Comment by HeddaZ** [comment]
可以理解你的想法，只是使用局部的快捷键会有一个比较棘手的问题。如果当前的窗体不具有焦点，那么这些快捷键可能都不会有效果，反而容易被人认为是bug。
本软件最初的设计意图就是【最轻量（最偷懒）、最简洁（最粗暴）】实现快速盯盘，并附加少量的辅助计算和标示功能。
因此此项需求，我暂且将它搁置，如果它影响到更多的应用，会考虑进行改善。

**Comment by HeddaZ** [comment]
暂不做修改。
