### ISSUE TITLE
希望能够提取一个搜索股票的快捷窗口

### ISSUE THREAD

**Issue by laolangcool** [HeddaZ/Shadowin#7]
现在似乎是只能自己从其他地方找到想关注的股票代码，再贴到sw里面？如果有快捷搜索的窗口或链接就更方便了。

**Comment by HeddaZ** [comment]
你好，这也是我近期正在计划的一个 enh，用的人多了，快速方便的需求要放第一位。
----------------
主要要考察一下新浪数据源里是否有现成的可用；这部分会给予**高优先级，尽快实现**的。

**Comment by HeddaZ** [comment]
正在开发下一个大版本，会将 shadowstock 全部重构一下；毕竟传统的 js 比不上 jquery 方便。

**Comment by HeddaZ** [comment]
问题已在 V2.0 中解决，请重新下载安装：https://github.com/HeddaZ/Shadowin/releases  （推荐升级方式）
抑或直接修改本地文件 `Shadowin.exe.config`：
&lt;add key=&quot;Url&quot; value=&quot;http://shadowstock.iihtml.com/&quot;/&gt;
