### ISSUE TITLE
关于单元格颜色显示的改进

### ISSUE THREAD

**Issue by laolangcool** [HeddaZ/Shadowin#8]
现在一行是同一个颜色，希望盈亏率和总盈亏能够根据正负来分别用红绿显示。

**Comment by laolangcool** [comment]
对于涨/跌停的，能否用深红/绿来与其他的区分开呢？

**Comment by HeddaZ** [comment]
这是一个不错的建议。下一个版本盈亏部分我会采用独立的着色方式。

**Comment by HeddaZ** [comment]
问题已在 V2.0 中解决，请重新下载安装：https://github.com/HeddaZ/Shadowin/releases  （推荐升级方式）
抑或直接修改本地文件 `Shadowin.exe.config`：
 <add key="Url" value="http://shadowstock.iihtml.com/"/>
