### ISSUE TITLE
输入框无法输入k，如何关注港股？

### ISSUE THREAD

**Issue by laolangcool** [HeddaZ/Shadowin#9]
港股代码格式应该是hk+代码吧，但在输入框里无法输入k……
随着关注的股市增多，发现现在的输入框真是难以胜任啊。我目前是把代码放在一个文本里，修改了再贴上去。防止若误操作把一堆的关注弄没了。

**Comment by lekai63** [comment]
试了下新浪的那个查询端口，整个数据格式应该也是支持港股的，比如hk03968，建议楼主修改输入框关于“数据规整化”的代码，以便支持港股。

**Comment by HeddaZ** [comment]
不好意思哦，目前港股的协议接口是一致的；但是反馈回来的列表的序号和栏位和 沪深不一致，所以无法快速兼容。
所以，该功能会考虑再下一个大版本中实现。

**Comment by lekai63** [comment]
借助楼主的代码 我自己修改了下以便其支持港股，并针对港股修改了数据结构，使得网页端能支持港股和沪深。目前放在个人的sae上用着（仅我个人使用，还望楼主见谅）。
发现一个问题：这个接口的港股数据是延时数据。因此我觉得对于使用影子证券的上班族而言用处不大。

**Comment by HeddaZ** [comment]
非常感谢你积极的工作，任何人愿意基于此项目做一些自己喜欢的事，我表示喜闻乐见
---------------------------------------------------------------------------------------------------------
** 在此也很高兴的通知你，ShadowStock V2.0 已经发布，整个代码已经彻底重构，并且通过模板化的列引擎设计使数据源更容易扩展；如果你有空，可以基于此来实现以下港股的盯盘功能；我会很乐意合并你贡献的代码！ **
  
* 请重新下载安装：https://github.com/HeddaZ/Shadowin/releases  （推荐升级方式）
* 抑或直接修改本地文件 `Shadowin.exe.config`：
&lt;add key=&quot;Url&quot; value=&quot;http://shadowstock.iihtml.com/&quot;/&gt;

**Comment by HeddaZ** [comment]
在此备注
=======
港股的新浪数据接口是（以腾讯为例）： 
`http://hq.sinajs.cn/rn=1439002235993&list=rt_hk00700`

数据源返回是： 
`var hq_str_rt_hk00700="TENCENT,腾讯控股,139.000,140.900,142.400,139.000,142.100,1.200,0.852,142.000,142.100,1525042660.300,10787723,44.606,0.200,171.000,104.500,2015/08/07,16:01:06";`
